### ISSUE TITLE
Prices?

### ISSUE THREAD

**Issue by be-green** [jabrell/pyeutl#6]
This is a super cool project, and data I didn't know existed until today. This might a silly question (and I didn't see this in the source data), but is there information about the price these units were traded at? So if one account holder purchases an EUA from another, for example, is the price of that transaction known? Would it be the prevailing market price at that time?

Anyway regardless this is really neat, thanks for putting all of this together.

**Comment by be-green** [comment]
This could also just be me completely misunderstanding the data so if that's the case please let me know.

**Comment by jabrell** [comment]
The EUTL only reports the transfer of allowances once the transaction is completed. We do not know whether the parties settled the transaction over an exchange platform, over-the-counter, or using some kind of forward contract. Therefore, we do not know the prices (if there are any at all for the respektive transaction).  Daily prices might not be a bad proxy but need to be collected from an additional source (see e.g. [Ember](https://ember-climate.org/data/data-tools/carbon-price-viewer/) or [Sandbag](https://sandbag.be/index.php/carbon-price-viewer/). It seems that many trades occur through forward contracts over the ICE. These will be mainly settled in December but it is difficult to provide a price for these.

**Comment by be-green** [comment]
Thank you so much! And what a fantastic resource.
