### ISSUE TITLE
How about Effort Sharing Regulation (ESR)?

### ISSUE THREAD

**Issue by KSilkThread** [jabrell/pyeutl#7]
Dear Jan, 

This issue may be related to the amazing work you have conducted here. I recently read about the European Union's Effort Sharing Regulation (ESR) (formerly decision - ESD). It seems that Non-ETS sectors' (agriculture, residential etc.) emissions are nationally maintained inside dedicated registers. The EU even seems to have teams of technical experts to annually audit these registers (see https://climate.ec.europa.eu/eu-action/effort-sharing-member-states-emission-targets/implementation-effort-sharing-decision_en). 

I wonder if these registers are open for the public (e.g. the German ESD register)? If yes, it would be interesting to spectate it. Are you aware about those ESD registers? (see https://climate.ec.europa.eu/eu-action/effort-sharing-member-states-emission-targets_en)

**Comment by jabrell** [comment]
Hi Karl,

the answer is for sure: Yes. The ESR is part of the same register as the EU ETS, i.e., transactions, allocation, compliance, ...  are reported within the EUTL (e.g. [https://ec.europa.eu/clima/ets/transactionsCompliance.do](https://ec.europa.eu/clima/ets/transactionsCompliance.do)). I have that on my list but currently lack a bit of time. I think I have done some notebooks to fetch and parse the data but need to integrate that into the package.

**Comment by jabrell** [comment]
ESD data are included in the May 2023 data release
